//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OOO_Petrovich.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class order
    {
        public int idOrder { get; set; }
        public int idUser { get; set; }
        public int idProduct { get; set; }
        public int idWorker { get; set; }
        public Nullable<System.DateTime> orderDate { get; set; }
        public Nullable<int> idStatus { get; set; }
        public string orderDescription { get; set; }
        public int orderCount { get; set; }
    
        public virtual product product { get; set; }
        public virtual status status { get; set; }
        public virtual user user { get; set; }
    }
}
